---
#            _     _     _        __          __     ___            _        
#  _ __ ___ (_)___| |_  (_) ___  / /__ _ __ __\ \   / / |_ __ _ ___| | _____ 
# | '_ ` _ \| / __| __| | |/ _ \| / __| '__/ __| | / /| __/ _` / __| |/ / __|
# | | | | | | \__ \ |_ _| | (_) | \__ \ | | (__| |/ / | || (_| \__ \   <\__ \
# |_| |_| |_|_|___/\__(_)_|\___/| |___/_|  \___| /_/   \__\__,_|___/_|\_\___/
#                                \_\          /_/                            
# tasks file for ar-mistio-src
- include: install-pkg.yml
- include: compile-src.yml
- include: make-config.yml
- include: boot-daemon.yml

