---
#            _     _     _        __          __     ___                     _ _               
#  _ __ ___ (_)___| |_  (_) ___  / /__ _ __ __\ \   / / |__   __ _ _ __   __| | | ___ _ __ ___ 
# | '_ ` _ \| / __| __| | |/ _ \| / __| '__/ __| | / /| '_ \ / _` | '_ \ / _` | |/ _ \ '__/ __|
# | | | | | | \__ \ |_ _| | (_) | \__ \ | | (__| |/ / | | | | (_| | | | | (_| | |  __/ |  \__ \
# |_| |_| |_|_|___/\__(_)_|\___/| |___/_|  \___| /_/  |_| |_|\__,_|_| |_|\__,_|_|\___|_|  |___/
#                                \_\          /_/                                              
# handlers file for ar-mistio-src
- name: Restart HAProxy
  become: false
  shell: >
    chdir={{ mistio.install}}
    ./bin/supervisorctl restart haproxy

- name: Reload FirewallD
  shell: firewall-cmd --reload

